/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#424843",
        "tertiary-fixed": "#dce4de",
        "inverse-on-surface": "#f1f1ef",
        "surface-container": "#eeeeec",
        "inverse-primary": "#adcfb4",
        "on-error-container": "#93000a",
        "tertiary-container": "#3e4641",
        "surface-container-high": "#e8e8e6",
        "surface-container-low": "#f4f4f2",
        "surface-tint": "#466550",
        "secondary": "#695d47",
        "primary": "#163422",
        "on-tertiary-fixed-variant": "#414944",
        "primary-fixed-dim": "#adcfb4",
        "on-primary-fixed-variant": "#2f4d39",
        "on-tertiary-fixed": "#161d19",
        "surface-variant": "#e2e3e1",
        "surface-dim": "#dadad8",
        "primary-container": "#2d4b37",
        "on-secondary-fixed": "#221a09",
        "on-primary-fixed": "#022110",
        "background": "#f9f9f7",
        "on-primary-container": "#99baa1",
        "surface-container-highest": "#e2e3e1",
        "tertiary": "#28302b",
        "outline": "#727972",
        "error": "#ba1a1a",
        "primary-fixed": "#c8ebd0",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c8c0",
        "secondary-fixed": "#f1e1c4",
        "on-secondary-fixed-variant": "#504531",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#d4c5a9",
        "tertiary-fixed-dim": "#c0c8c2",
        "inverse-surface": "#2f3130",
        "on-tertiary": "#ffffff",
        "secondary-container": "#f1e1c4",
        "on-tertiary-container": "#acb4ad",
        "surface": "#f9f9f7",
        "surface-bright": "#f9f9f7",
        "on-secondary-container": "#6f634c",
        "on-background": "#1a1c1b",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1b",
      },
    },
  },
  plugins: [],
}